#!/bin/bash

# This script sets file extraction from known protocols and password extraction
echo "@load policy/frameworks/files/extract-all-files" >> /usr/local/bro/share/bro/bro-extra/bro-extra.bro
#log passwords
sed -i "s/default_capture_password = F/default_capture_password = T/" /usr/local/bro/share/bro/base/protocols/ftp/info.bro
sed -i "s/default_capture_password = F/default_capture_password = T/" /usr/local/bro/share/bro/base/protocols/http/main.bro

/bin/bash
