#!/bin/bash
# This script sets all logs to elasticsearch
echo "@load ./logs-to-elasticsearch" >> /usr/local/bro/share/bro/bro-extra/bro-extra.bro
#This script adds pcap url per socket in conn logs
echo "@load ./conn_pcap.bro" >>  /usr/local/bro/share/bro/bro-extra/bro-extra.bro
# enable extraction
echo "@load policy/frameworks/files/extract-all-files" >>  /usr/local/bro/share/bro/bro-extra/bro-extra.bro
# This script sets file extraction from known protocols and adds an uri to the extracted files
echo "@load base/files/extract" >> /usr/local/bro/share/bro/bro-extra/bro-extra.bro
# stop local logging
sed -i "s/default_writer = WRITER_ASCII/default_writer = WRITER_NONE/g" /usr/local/bro/share/bro/base/frameworks/logging/main.bro
#log passwords
sed -i "s/default_capture_password = F/default_capture_password = T/" /usr/local/bro/share/bro/base/protocols/ftp/info.bro
sed -i "s/default_capture_password = F/default_capture_password = T/" /usr/local/bro/share/bro/base/protocols/http/main.bro
#start supervisor daemon
/usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf
export DOCKERHOST=$1
cp /usr/local/bro/share/bro/bro-extra/extract_files_template.bro /usr/local/bro/share/bro/base/files/extract/main.bro
sed -i "s/DOCKERHOST/${DOCKERHOST}/g" /usr/local/bro/share/bro/base/files/extract/main.bro

#pcap file and settings
export PCAPFILE=`tempfile -d /bro/pcap -p bro- -s .pcap`
cp /usr/local/bro/share/bro/bro-extra/conn_pcap_template.bro /usr/local/bro/share/bro/bro-extra/conn_pcap.bro
sed -i "s:PCAPFILE:${PCAPFILE}:" /usr/local/bro/share/bro/bro-extra/conn_pcap.bro
sed -i "s/DOCKERHOST/${DOCKERHOST}/g" /usr/local/bro/share/bro/bro-extra/conn_pcap.bro
# set file permissions for apache
chown www-data:www-data ${PCAPFILE}
chmod a+r ${PCAPFILE}
#cmd
bro -r - -w ${PCAPFILE}
